version: '3'
services:
  dynamo:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - 8000:8000
  tests:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - dynamo
    environment:
      AWS_DYNAMO_URL: http://dynamo:8000
      AWS_DEFAULT_REGION: us-west-2
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    entrypoint:
      - bash
      - -c
      - "cd /app; ./bootstrap.sh; env && npm run test"